version: '3.8'

services:
  lms-admin-panel:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env.docker
    restart: unless-stopped
    networks:
      - lms-network

networks:
  lms-network:
    external: true
